"""Where the process finds its versioned artifacts on disk.

In a source checkout the repo root is derived from this file's location; in a
container the package lives in site-packages, so the image sets ``DW_REPO_ROOT``
(``/app``) and ships ``configs/``, ``evals/fixtures/`` and ``contracts/release/``
at that root.

Every path the composition root reads is named here rather than spelled inline,
so a deployment that relocates one file changes one line.
"""

from __future__ import annotations

import os
from pathlib import Path

REPO_ROOT = Path(os.environ.get("DW_REPO_ROOT", str(Path(__file__).resolve().parents[5])))

CONFIGS = REPO_ROOT / "configs"
MODEL_PROFILES_DIR = CONFIGS / "models"
PROMPTS_DIR = CONFIGS / "prompts"
TOOL_SPECS_DIR = CONFIGS / "tools"
TOOLSETS_DIR = CONFIGS / "toolsets"
WORKERS_DIR = CONFIGS / "workers"
POLICIES_DIR = CONFIGS / "policies"
COPY_DIR = CONFIGS / "copy"

# The platform's own user-facing words, versioned like a prompt bundle so a
# deployment can change them without a release.
# 1.4.0 is 1.3.0 verbatim plus the context-compaction text; a worker that wires
# compaction refuses to start on anything older.
RUNTIME_COPY_CONFIG = CONFIGS / "copy" / "runtime@1.6.0.yaml"
WORKER_RUN_POLICY = POLICIES_DIR / "worker_runs@1.0.0.yaml"
ATTACHMENT_POLICY = POLICIES_DIR / "attachment_ingest@1.1.0.yaml"

MOCK_MODEL_FIXTURES = REPO_ROOT / "evals" / "fixtures" / "mock_model"
_RELEASE_MANIFEST_REF = REPO_ROOT / "contracts" / "release" / "manifest.ref"


def release_manifest_ref() -> str:
    """The content-addressed release this process is serving.

    Generated by ``make release-manifest``; every run records it so a result can
    be traced back to the exact artifact set that produced it. Absent only in
    un-released development trees.
    """
    if _RELEASE_MANIFEST_REF.exists():
        return _RELEASE_MANIFEST_REF.read_text(encoding="utf-8").strip()
    return "unreleased"
